name: Linux

on:
  push:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
        sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
        sudo apt update
        sudo apt install -y ffmpeg zlib1g libavfilter-dev libswresample-dev libavdevice-dev libavcodec-dev libavformat-dev libavutil-dev pkg-config
    - name: Build
      run: cargo build --release --bin mxc --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: mxc_linux
        path: target/release/mxc

    - name: continuous release
      uses: softprops/action-gh-release@v1
      if: github.ref_name == 'main'
      with:
        prerelease: true
        files: target/release/mxc
        tag_name: continuous
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
