name: Release setup

on:
  push:
    branches:
      - '*'

jobs:
  release-setup:
    runs-on: ubuntu-latest
    steps:

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref_name == 'main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous release"