name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
        sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
        sudo apt update
        sudo apt install -y ffmpeg zlib libavfilter-dev libswresample-dev libavdevice-dev libavcodec-dev libavformat-dev libavutil-dev pkg-config
    - name: Build
      run: cargo build --bin mxc --verbose
